server.port=9090

# Telegram API
telegram.api.url=https://api.telegram.org/bot
telegram.bot.id=8780418145:AAFx1D363bvajpZLmn0xQWQErLObkFraZCc

#OpenWeatherMap
open.weather.api.url=https://api.openweathermap.org/data/2.5/weather
open.weather.api.token=c8c9876314602e9a4581205284ae9911